# Server Configuration
server.port=${SERVER_PORT:8080}

# S3 Compatible Configuration
# Use environment variables to inject sensitive data
aws.s3.access-key=${AWS_ACCESS_KEY_ID}
aws.s3.secret-key=${AWS_SECRET_ACCESS_KEY}
aws.s3.region=${AWS_REGION:us-west-2}
aws.s3.bucket=${AWS_BUCKET_NAME:afsaihubggufcos}
# Optional: Override endpoint for S3 Compatible storage (e.g. http://localhost:9000)
aws.s3.endpoint=${AWS_ENDPOINT_URL:}
